### ISSUE TITLE
Strange website in nitro properties

### ISSUE THREAD

**Issue by isahann** [Holo5/nitro-docker#10]
Is there a reason for this property to contain this (somehow shady) website? 

https://github.com/Holo5/nitro-docker/blob/7b92e3cf9a4428d3f3f6bd3ef9c2012c95ff07eb/nitro/configuration/nitro-react/public/ui-config.json#L4

**Comment by Pi-Bouf** [comment]
Wtf is that

I will fix that immediatly

**Comment by Pi-Bouf** [comment]
I fixed that, sorry for your eyes 🙏🏾

**Comment by isahann** [comment]
Thanks man! I've closed the issue myself after some code analysis, I think this URL might be related to some sort of place to store the pictures taken from in-game or something like it. But thanks anyaway!
