### ISSUE TITLE
Remote connection

### ISSUE THREAD

**Issue by Nigcra** [Holo5/nitro-docker#11]
What to do to connect from other hosts? I found hardcoded '127.0.0.1' in different files but I can't connect even to that localhost because I installed in a VM.

**Comment by Pi-Bouf** [comment]
Hey ! Hardcoded because it's the loopback address, it must work outside

Do you use it in a VM like VirtualBox ? Or WSL ? Or something else ?

It's really for dev purpose, not production

**Comment by Pi-Bouf** [comment]
Oooh that's normal !

You need to extract every assets :)

Run the following command `just extract-nitro-assets`

**Comment by Nigcra** [comment]
![image](https://github.com/Holo5/nitro-docker/assets/26165631/6be0fe80-0dfd-4014-a74b-4da2ef498f06)
Thought I had done that correctly so far

**Comment by Pi-Bouf** [comment]
It works now ?

You a have a lot of errors too...

**Comment by Nigcra** [comment]
No, the error pattern is the same. I had already run the command as described in the readme before I even opened the browser. It is a fresh VM, fresh Docker.io, Compose and Just.

Why it brings these errors when extracting the SWF I don't know, I did nothing more than check out Git head and proceed according to readme. In between it also looks like many SWF are working.

**Comment by Pi-Bouf** [comment]
That's strange... do you have in the bundled folder the ExternalText.json ? 🤔

**Comment by Nigcra** [comment]
![image](https://github.com/Holo5/nitro-docker/assets/26165631/ee644f9e-3c93-4fe0-ac07-efa91aabdc6e)
It looks like I don't have the folder, nor the file 😶

**Comment by Pi-Bouf** [comment]
I'm sorry, really don't know :/ Check in configuration of the nitro-extractor and debug it if you can

**Comment by Nigcra** [comment]
hm, I really don't know how to debug there

**Comment by Nigcra** [comment]
Okay, beside the converter problem, the ExternalTexts.json is there:
`@habbo:~/holo5/nitro/nitro-converter/assets/gamedata# ls
EffectMap.json  ExternalTexts.json  FigureData.json  FigureMap.json  FurnitureData.json  ProductData.json
`

But the browser says it cannot be loaded: 
![image](https://github.com/Holo5/nitro-docker/assets/26165631/6142b8a7-349a-461b-93b7-e526465ffa1d)
Which brings me back to the first post - I'm running it on a VM so 127.0.0.1 cannot work. Where can I change the URL?

**Comment by Pi-Bouf** [comment]
You can't change the URL, only ports ! It's inside the docker-compose, look at `8080`

**Comment by Nigcra** [comment]
Its weird because some assets are loading with the correct IP - I can see the get requests. Thought there would be some kind of BASE_URI.

**Comment by Nigcra** [comment]
Thanks for your efforts and time!! :)

**Comment by Pi-Bouf** [comment]
OK I tried to install everything from scratch though a brand new WSL instance.

And it works ! I can't help you more on that, except if you add me on Discord :)

Good luck. (close this issue if you want)

**Comment by Nigcra** [comment]
I fixed it myself by changing the webclient configuration in:
` nitro/configuration/nitro-react/public`
to the current VM IP / DNS name.

![image](https://github.com/Holo5/nitro-docker/assets/26165631/871cce79-40f6-4616-9441-da3b57b43a52)

btw: wasn't the camera.com removed in the code? something seems to still be there
