### ISSUE TITLE
20% infinite loading

### ISSUE THREAD

**Issue by Gisleude** [Holo5/nitro-docker#12]
Hi Guys, 

I recently tried to start a project using nitro-docker to create the Habbo server. 

Unfortunelly i'm facing this issue:
![image](https://github.com/Holo5/nitro-docker/assets/14363697/6e178536-0434-4602-9945-ffc1cdf29e4e)

Has anyone also faced this issue?

**Comment by Gisleude** [comment]
Issue solved using:
just extract-nitro-assets

thanks guys.

**Comment by Pi-Bouf** [comment]
Perfect, well done !
