### ISSUE TITLE
40% on loading screen + Connection failed (WS failed)

### ISSUE THREAD

**Issue by belicfr** [Holo5/nitro-docker#18]
Hello,

I've installed nitro-docker like Readme said to do. But when I open `127.0.0.1:1080/?sso=123`, I get a **Connection failed** with an error in the JS console (see image).
I've searched on Google, and the solutions do not work for me.

Anyone can help me?

Thanks!

**Image:**
![image](https://github.com/Holo5/nitro-docker/assets/96206878/9bc701c8-b6f5-48b3-a738-6bc8434c58d4)

**Comment by Pi-Bouf** [comment]
OK It was the link to download the NitroWebsocket plugin. 
I changed to the official one coming from git.krews.org :)

Fix is here: https://github.com/Holo5/nitro-docker/commit/3a6af707d93e4919a90b2d816cd487e4a1e0cc1b
