### ISSUE TITLE
Issues with just start-all

### ISSUE THREAD

**Issue by EzpadaZ** [Holo5/nitro-docker#19]
Hi, i know this project is old but i want to ask if it still is supposed to run or am i missing something?

I reinstalled docker with WSL2 and trying the steps i see that arcturus fails to build with the following output :

> arcturus  | [INFO] Scanning for projects...
> arcturus  | [INFO] ------------------------------------------------------------------------
> arcturus  | [INFO] BUILD FAILURE
> arcturus  | [INFO] ------------------------------------------------------------------------
> arcturus  | [INFO] Total time:  0.148 s
> arcturus  | [INFO] Finished at: 2024-03-13T06:00:59Z
> arcturus  | [INFO] ------------------------------------------------------------------------
> arcturus  | [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/app). Please verify you invoked Maven from the correct directory. -> [Help 1]
> arcturus  | [ERROR]
> arcturus  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> arcturus  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> arcturus  | [ERROR]
> arcturus  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
> arcturus  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
> arcturus  | Connecting to git.krews.org (172.67.217.194:443)
> arcturus  | wget: server returned error: HTTP/1.1 400 Bad Request

And nitro is stuck on this without any further output :(

> nitro     | [4/4] Building fresh packages...
> nitro     | Done in 24.20s.
> : not found /app/scripts/build.sh: line 7:
> : not found /app/scripts/build.sh: line 8:
> nitro     | unix:///run/supervisord.sock no such file
> nitro     | unix:///run/supervisord.sock no such file
> nitro     | unix:///run/supervisord.sock no such file
> : not found /app/scripts/build.sh: line 12:

I tought this was it but site isnt accesible :/
Any ideas? 
Thanks in advance!

**Comment by EzpadaZ** [comment]
The solution is to run the commands **inside** the linux terminal and not in powershell/CMD.

I originally tought this only needed  WSL2 Support enabled in windows + docker and i could run everything from windows.

**Comment by Pi-Bouf** [comment]
Ouh, nice catch ! <3
