### ISSUE TITLE
Stuck at 20% and build failure

### ISSUE THREAD

**Issue by larsassink** [Holo5/nitro-docker#21]
Hi there, I have the following two errors after following the instructions:

It's a fresh ubuntu vm on Proxmox

<img width="1637" alt="Screenshot 2024-07-17 at 17 26 55" src="https://github.com/user-attachments/assets/fe89881a-d7b6-4b69-8cfb-10e411df070f">
<img width="1596" alt="Screenshot 2024-07-17 at 17 27 10" src="https://github.com/user-attachments/assets/ed7805d7-faf5-451e-94a3-983decdb9598">

**Comment by Pi-Bouf** [comment]
Hello ! Sad issue yes...

did you tried elsewhere ? Like on local env?

**Comment by Jeuns2france** [comment]
I have the same issue unfortunately, on my ubuntu machine everything is working fine but when i log with my vm IP on my host PC it gets stuck at 20%. I get these values in my emulator_settings : 
<img width="202" alt="image" src="https://github.com/user-attachments/assets/8ac5bba4-7eda-4661-8e3c-460c9665bc87">

**Comment by larsassink** [comment]
I have not tried on a local env. Wanted to do it on Proxmox so I can share access with others.

**Comment by cxdy** [comment]
Need to run `just extract-nitro-assets` afterwards.

Btw @larsassink what terminal are you using? Looks sick

**Comment by Pi-Bouf** [comment]
Yop ! I retried both from mac os m3 and one from wsl on windows.

Bot are a success, I didn't get stuck at all, everything working well :( 

Maybe looking at your console you will see a miss like 'ExternalText.json' not found, or something like that :)

**Comment by larsassink** [comment]
> Need to run `just extract-nitro-assets` afterwards.
> 
> Btw [@larsassink](https://github.com/larsassink) what terminal are you using? Looks sick

@Jeuns2france 
Didn't see your message till now, the terminal is [Termius](https://termius.com/)!
