### ISSUE TITLE
Unable to update url base from redirection

### ISSUE THREAD

**Issue by deffcolony** [Holo5/nitro-docker#5]
Hello @Pi-Bouf @iamgpe, everyone.

I did the following command inside the cloned repo: **git submodule update**

Some redirections are failed to fetch...

and this repo --> https://git.krews.org/morningstar/arcturus-morningstar-default-swf-pack.git/' **okay they restored their repo**

fatal: unable to update url base from redirection:
  asked for: https://git.krews.org/nitro/nitro-converter.git/info/refs?service=git-upload-pack
   redirect: https://github.com/billsonnn?tab=repositories
fatal: clone of 'https://git.krews.org/nitro/nitro-converter.git' into submodule path '/home/axdocker/docker/nitro-docker/nitro/nitro-converter' failed
Failed to clone 'nitro/nitro-converter'. Retry scheduled

Cloning into '/home/axdocker/docker/nitro-docker/nitro/nitro-react'...
fatal: unable to update url base from redirection:
  asked for: https://git.krews.org/nitro/nitro-react.git/info/refs?service=git-upload-pack
   redirect: https://github.com/billsonnn?tab=repositories
fatal: clone of 'https://git.krews.org/nitro/nitro-react.git' into submodule path '/home/axdocker/docker/nitro-docker/nitro/nitro-react' failed
Failed to clone 'nitro/nitro-react'. Retry scheduled

Cloning into '/home/axdocker/docker/nitro-docker/nitro/nitro-swf'...
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://git.krews.org/morningstar/arcturus-morningstar-default-swf-pack.git/' not found
fatal: clone of 'https://git.krews.org/morningstar/arcturus-morningstar-default-swf-pack.git' into submodule path '/home/axdocker/docker/nitro-docker/nitro/nitro-swf' failed
Failed to clone 'nitro/nitro-swf'. Retry scheduled

Cloning into '/home/axdocker/docker/nitro-docker/nitro/nitro-converter'...
fatal: unable to update url base from redirection:
  asked for: https://git.krews.org/nitro/nitro-converter.git/info/refs?service=git-upload-pack
   redirect: https://github.com/billsonnn?tab=repositories
fatal: clone of 'https://git.krews.org/nitro/nitro-converter.git' into submodule path '/home/axdocker/docker/nitro-docker/nitro/nitro-converter' failed
Failed to clone 'nitro/nitro-converter' a second time, aborting

can you please update the github repo so the files do exist when i try to fetch those? or atleast just upload them here so i only have to clone this github repo and just do the **docker-compose up -d**

**Comment by Pi-Bouf** [comment]
Oh yes you're right, a lot of things changed since my last edit !
Can you create a pull request with fixes ?

Or I need to do it ?

**Comment by Gurkengewuerz** [comment]
Oh, interesting. Just found this repository a few hours ago while I was in nostalgia with habbo.
Because I wanted some kind of docker installation, I am writing my own project. Probably make it public tomorrow.
It uses no build system, just docker compose for bootstrapping and running the services.
I really appreciate your work on this repository.

**Comment by Pi-Bouf** [comment]
Nice work !
